version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map the backend port
    environment:
      MONGO_URI: mongodb://mongo:27017/splittify
      JWT_SECRET_KEY: NotAVerySecureKey
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
